# Generated by Django 2.2.12 on 2021-09-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_posted', models.CharField(max_length=200, null=True)),
                ('image_url', models.URLField(max_length=1000)),
                ('likes', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
