# Generated by Django 2.2.12 on 2021-09-19 23:12

from django.db import migrations, models
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.AddField(
            model_name='post',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=django_jsonfield_backport.models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='post',
            name='who_posted',
            field=models.CharField(max_length=200),
        ),
    ]
