# Generated by Django 2.2.12 on 2021-09-19 23:12

from django.db import migrations, models
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210919_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=django_jsonfield_backport.models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='who_posted',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
