# Generated by Django 2.2.12 on 2021-09-20 03:59

from django.db import migrations, models
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210919_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked_by',
            field=django_jsonfield_backport.models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
