# Generated by Django 2.2.12 on 2021-09-20 07:18

from django.db import migrations
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210920_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=django_jsonfield_backport.models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='post',
            name='liked_by',
            field=django_jsonfield_backport.models.JSONField(default=dict),
        ),
    ]
