# Generated by Django 2.2.12 on 2021-09-20 21:07

from django.db import migrations
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210920_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=django_jsonfield_backport.models.JSONField(default=list),
        ),
    ]
